### PR TITLE
Fix re aborting

### PR DESCRIPTION
**Pull request by jrgm**
@dannycoates - this is @seanmonstar's suggestion to address a problem seen in production where  if auth-db-mysql blocked for a bit, auth-server would emit nodejs EE warnings for too many listeners, and after that there was a steady leak. I'd still like to understand what the actual leak was, but this change seems reasonable: only abort the request on the initial timeout.

Also includes updates to .travis.yml to add node 4 and 6. If you want `stable` in there too, I will add it. nodejs 0.8 appears to having issues building with some npm dependencies and fails. Is it time to drop 0.8 support for this module?

### CODE REVIEW

**Comment by dannycoates** [comment]
Thanks @jrgm. This module probably needs a good tune up for node > 0.10. I haven't dug into it but the ['abort' event](https://nodejs.org/dist/latest-v4.x/docs/api/http.html#http_event_abort) was added after this was written. It should probably handle that somehow.

**Comment by vladikoff** [comment]
@dannycoates @jrgm should we just drop 0.8 support for this?

**Comment by dannycoates** [comment]
> should we just drop 0.8 support for this?

I think that's fine. 

I would like to see what happens when handling the 'abort' event instead of checking the timedOut flag. @jrgm is that something you can easily try?

**Comment by jrgm** [comment]
Yeah, I can try it out in stage with load if you give me a patch.

**Comment by jrgm** [comment]
Closing this in favour of https://github.com/dannycoates/poolee/pull/22

**Pull request closed without merging**
